// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4DnKgYiXdrBaStfaLzpdZrf1hsjKVwWI',
    appId: '1:754695461905:web:a8f1658627a4a13be3a5b0',
    messagingSenderId: '754695461905',
    projectId: 'minute-diary-fdc63',
    authDomain: 'minute-diary-fdc63.firebaseapp.com',
    storageBucket: 'minute-diary-fdc63.appspot.com',
    measurementId: 'G-RR5MVYWK2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn4kZ7V0ICRS_chbVC1ngIR2549nDvGLw',
    appId: '1:754695461905:android:8c745592e6c0c0ebe3a5b0',
    messagingSenderId: '754695461905',
    projectId: 'minute-diary-fdc63',
    storageBucket: 'minute-diary-fdc63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7NQ1k-eddIYvhETsMo04J8fslxLtTd0Q',
    appId: '1:754695461905:ios:b717199e770f65b6e3a5b0',
    messagingSenderId: '754695461905',
    projectId: 'minute-diary-fdc63',
    storageBucket: 'minute-diary-fdc63.appspot.com',
    iosBundleId: 'com.example.threeMinuteDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7NQ1k-eddIYvhETsMo04J8fslxLtTd0Q',
    appId: '1:754695461905:ios:b22ca220cbd12677e3a5b0',
    messagingSenderId: '754695461905',
    projectId: 'minute-diary-fdc63',
    storageBucket: 'minute-diary-fdc63.appspot.com',
    iosBundleId: 'com.example.threeMinuteDiary.RunnerTests',
  );
}
